name: combine1
on:
  push:
    branches:
      - master # Adjust this to match the branch you want to trigger the workflow for

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Activity Automation
        run: |
          aws cloudformation deploy \
            --stack-name creationstack \
            --template-file .github/workflows/automate.yaml \
            --capabilities CAPABILITY_NAMED_IAM
        
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}


